import {
  Building2,
  Car,
  Droplets,
  Flame,
  GraduationCap,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  PartyPopper,
  PawPrint,
  RefreshCw,
  Shapes,
  ShieldCheck,
  ShoppingBasket,
  Wrench,
  Zap,
} from 'lucide-react';

export const categoryIcons = Object.freeze({
  Building2,
  Car,
  Droplets,
  Flame,
  GraduationCap,
  HeartPulse,
  House,
  Landmark,
  Laptop,
  PartyPopper,
  PawPrint,
  RefreshCw,
  Shapes,
  ShieldCheck,
  ShoppingBasket,
  Wrench,
  Zap,
});

export const categoryIconLabels = Object.freeze({
  Building2: 'Edificio',
  Car: 'Vehículo',
  Droplets: 'Agua',
  Flame: 'Gas o calefacción',
  GraduationCap: 'Educación',
  HeartPulse: 'Salud',
  House: 'Vivienda',
  Landmark: 'Administración',
  Laptop: 'Tecnología',
  PartyPopper: 'Ocio',
  PawPrint: 'Mascotas',
  RefreshCw: 'Suscripción',
  Shapes: 'Otros',
  ShieldCheck: 'Seguro',
  ShoppingBasket: 'Compra',
  Wrench: 'Servicio',
  Zap: 'Electricidad',
});

export const categoryIconOptions = Object.keys(categoryIcons);
